# Programs to be run before every commit, to ensure code quality

repos:
  # Alphabetically sort imports and group into standard library, third party, and local imports
  - repo: https://github.com/pre-commit/mirrors-isort.git
    rev: v5.7.0
    hooks:
      - id: isort
        name: Sort imports

  # Use the Uncompromising Code Formatter on code and code blocks in documentation
  - repo: https://github.com/ambv/black.git
    rev: 20.8b1
    hooks:
      - id: black
        name: Run black format code

  - repo: https://github.com/asottile/blacken-docs.git
    rev: v1.9.2
    hooks:
      - id: blacken-docs
        name: Format code blocks in docs

  # Check `noqa` statements
  - repo: https://github.com/pre-commit/pygrep-hooks.git
    rev: v1.7.1
    hooks:
      - id: python-use-type-annotations
        name: python-check-blanket-noqa

  # Various minor formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
      - id: check-yaml
        name: Check YAML files
      - id: trailing-whitespace
        name: Check trailing whitespace
        exclude: (?x)^(doc/analysis.org)$
      - id: end-of-file-fixer
        name: Check files end in single new line
      - id: mixed-line-ending
        name: Check for uniform line endings
      - id: check-executables-have-shebangs
        name: Check executables have shebangs

  # Finally, run a static code checker to look for errors
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.4
    hooks:
      - id: flake8
        name: Run flake8 static code checker

  # Hooks to check these hooks
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: Check hooks apply
      - id: check-useless-excludes
        name: Check for useless hook excludes
